### ISSUE TITLE
0.15.0-preview requires azure-core 0.1.13

### ISSUE THREAD

**Issue by sbonebrake** [Azure/azure-storage-ruby#106]
When trying to make calls with versions <= azure-core-0.1.12 . I get
```
ArgumentError: wrong number of arguments (5 for 2..4)
from /Users/scbone/.rvm/gems/ruby-2.1.10/gems/azure-core-0.1.12/lib/azure/core/signed_service.rb:40:in `call'
```
Using azure-core 0.1.13 seems to fix this issue. @yaxia

**Comment by yaxia** [comment]
Yes, it expected. Because `azure-storage 0.15.0-preview` added the supports for secondary location access and retry logic according to the location mode setting. It relies on the `azure-core 0.1.13` which added request options in the retry data.

Is there any reason that prevents you from updating to the latest `azure-core`?

**Comment by sbonebrake** [comment]
Nothing that prevents it, but the gemspec should be updated. If it's not updated bundler won't force an upgrade versions of azure-core.

**Comment by yaxia** [comment]
Thanks for clarifying. `azure-storage.gemspec` is using `s.add_runtime_dependency("azure-core", "~> 0.1")`, so 0.1.13 is supposed be installed with a fresh installation. For the updating story, I'd suggest to use `bundle update azure-storage`, that will update the latest dependencies.

**Comment by yaxia** [comment]
It is resolved in GA version.
