### ISSUE TITLE
Unable to list blobs

### ISSUE THREAD

**Issue by dylan-azucena** [Azure/azure-storage-ruby#114]
I am unable to list blobs via the `azure-storage-blob` gem. Doing the following:
```
require 'azure/storage/blob'
...
client = Azure::Storage::Blob::BlobService.create(storage_account_name: storage_account, storage_access_key: access_key)

client.list_blobs(container)
```
where I'm specifying `storage_account`, `access_key`, and `container` as my Azure storage account with its respective access key, and a container within that storage account. I get back an empty list for all of my containers, even though they have hundreds of blobs.

However, I'm pretty sure that there is nothing wrong with my access method since I can successfully perform other functions, such as `list_containers`. The result of `client.list_containers`:
```
[#<Azure::Storage::Blob::Container::Container:0x007fa570354428
  @metadata={},
  @name="{container-name}",
  @properties=
   {:last_modified=>"Thu, 28 Sep 2017 18:49:08 GMT",
    :etag=>"{etag}",
    :lease_status=>"unlocked",
    :lease_state=>"available"},
  @public_access_level=nil>,
 #<Azure::Storage::Blob::Container::Container:0x007fa570345e28
  @metadata={},
  @name="{another-container-name}",
  @properties=
   {:last_modified=>"Wed, 14 Jun 2017 13:23:31 GMT",
    :etag=>"{etag}",
    :lease_status=>"unlocked",
    :lease_state=>"available"},
  @public_access_level=nil>]
``` 
I also attempted to list blobs using an SAS but same result. I _am_ able to list blobs in my containers via the Azure CLI, so I don't think it's an issue with my containers/storage account.

**Comment by katmsft** [comment]
Hi @dylan-azucena , thanks for reporting the problem, I'm now checking on the code and trying to repro the problem.

**Comment by katmsft** [comment]
BTW @dylan-azucena , did it return a continuation token to you? could you please check if `result.continuation_token` is empty?

**Comment by katmsft** [comment]
Also, if you could enable the debug filter, and give me the request ID for your listing blob request, that would be very helpful for us to debugging the problem with server log. Thanks!

**Comment by dylan-azucena** [comment]
I do get a continuation token doing:
```
result = client.list_blobs(container)

result.continuation_token
```
From debug filter:
```
"x-ms-request-id"=>"fae3c13f-001e-00bf-1e70-90822e000000"
```

**Comment by katmsft** [comment]
@dylan-azucena Thanks for the response. The `list_blobs` actually is behaving correctly. Sometimes when you list blobs, the blobs are too long and server could not return the full list in time. Instead of waiting for the server to finish, it returns a continuation token for you to query again. So as long as you receive a non-null continuation token, your list is incomplete and you need to call it again querying for more items, it applies to all the list/query commands of this SDK.
Please see [here](https://github.com/Azure/azure-storage-ruby/blob/b53d4360e360afe7eda41a0c12899d49ff73ccc1/blob/lib/azure/storage/blob/container.rb#L562-L567) for how to use the continuation token.

**Comment by dylan-azucena** [comment]
@katmsft Got it, thank you!
