### ISSUE TITLE
Strange blob upload API response

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-storage-ruby#115]
We are trying to upload a blob using SAS(Shared access signature) token. For generating SAS token we are doing:

```
ss = Azure::Storage::Core::Auth::SharedAccessSignature.new(<account_name>, <storage_account_key>)
token = ss.generate_service_sas_token("<container>/<blob_to_upload>", {:service=>"b", :resource=>"b", :permissions=>"w"})

https://account_name.blob.core.windows.net/<container>/<blob_to_upload>?<token>
Headers:
x-ms-blob-type: BlockBlob
Content-Type: text/plain
Content-Length: 4
```

We are getting three kinds of response for tokens generated at different times but with exacly same parameter.

- Signature fields not well formed
- Signature did not match. String to sign used was ....
- Successful

This is stopping us from providing upload feature for blob store

Adding @tarrygo who originally created the issue.

**Comment by yaxia** [comment]
@sarangan12 @tarrygo , could you please provide these information for investigation:
1. What the version of azure-storage that generates the SAS? Or you can provide the SAS, stripping the `sig=` part.
2. Can you provide the request Id for the failed requests: (It can be found in the response body)
- Signature fields not well formed
- Signature did not match. String to sign used was ....

**Comment by tarrygo** [comment]
@yaxia I have tried 0.12.0.preview and 0.15.0.preview versions of azure-storage
Failure case:
signature
sig=RT%2BZNBBUn27%2BuyzDXWEvL7Go%2BUS%2Fut57S86UF%2FEVZwg%3D
signature_id = ed58e31d-001e-004b-0506-9592e0000000 
Response: 
`<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>AuthenticationFailed</Code>
    <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ed59b791-001e-004b-5707-9592e0000000
Time:2018-01-24T11:33:20.9614071Z</Message>
    <AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>`

Sucess case:
signature:
sig=6vLIs5yyNn8mzUNhbQUk%2F8d32oTf6CqYYo27c3p%2Fs4w%3D

**Comment by yaxia** [comment]
It seems you were sending request from Postman. Though I cannot see the signature in the log, but I found the value in expiry (se=) was URL decoded, i.e.: se=2018-01-25T07%3A12%3A27Z became se=2018-01-25T07:12:27Z.
I’d guess some characters in the signature were decoded as well such as %2B(+), except the mandatories ones, such as: %2F(/), %3D(=), etc. If that is the case, then it explains some requests got passed, because there is no “%2B” in the signature.

You might want to use the latest version of Postman or just send the request using `azure-storage` gem, the code should be pretty simple.
