### ISSUE TITLE
Azure::Storage::Blob::BlobService#create_block_blob return many nil properties

### ISSUE THREAD

**Issue by adrianodennanni** [Azure/azure-storage-ruby#116]
Hello!

After succesfully uploading a string via `Azure::Storage::Blob::BlobService#create_block_blob`, the `Azure::Storage::Blob::Blob` returned object misses many properties, such as `content_type` and `content_length`.

Example:
```
Azure::Storage::Blob::BlobService.new.create_block_blob('container1','hello','{"hello":"world"}',{content_type: 'application/json'}) 
# returns this:
#<Azure::Storage::Blob::Blob:0x0000000339c710 @properties={
  :last_modified=>"Fri, 26 Jan 2018 18:23:31 GMT",
  :etag=>"\"0x8D564E9E7604931\"",
  :lease_status=>nil,
  :lease_state=>nil,
  :lease_duration=>nil,
  :content_length=>nil,
  :content_type=>nil,
  :content_encoding=>nil,
  :content_language=>nil, 
  :content_disposition=>nil,
  :content_md5=>"+8JLzHoXlHWPwTJ/z+va9g==",
  :cache_control=>nil, 
  :blob_type=>nil,
  :copy_id=>nil,
  :copy_status=>nil,
  :copy_source=>nil,
  :copy_progress=>nil, 
  :copy_completion_time=>nil,
  :copy_status_description=>nil},
 @metadata={}, @encrypted=true, @name="hello">
```

The object was uploaded, since I am able to retreive it via #get_blob('container1', 'hello').

**Comment by katmsft** [comment]
Hi @adrianodennanni , thanks for reporting the issue.
Please find in the document of [Put blob](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob), which is the API this `create_block_blob` is calling when content are small, that the response has very limited information. Since the library has a different behavior than [azure-storage-net](https://github.com/Azure/azure-storage-net) library that also returns the request information to the user, we simply parse the response headers and return it to the user, therefore you see those nil object.
If you want more details of the blob, you must call `get_blob_properties`. Because it is a billable action, we do not call this for our user secretly after creating a blob.

**Comment by adrianodennanni** [comment]
Thanks for the answer. Therefore, I am closing this issue.
