### ISSUE TITLE
 High severity vulnerability in nokogiri - XML External Entity (XXE) Injection

### ISSUE THREAD

**Issue by habibbhutto** [Azure/azure-storage-ruby#126]
The details are given here
https://snyk.io/vuln/SNYK-RUBY-NOKOGIRI-20299

It is highlighted here (search keyword 'nokogiri')
https://snyk.io/stateofossecurity/

This vulnerability was disclosed on 11th January 2017. Nokogiri seems to be waiting for fix in upstream. Is there some possible work around to it or Is it possible for you to switch over to some other library instead?

**Comment by yaxia** [comment]
@habibbhutto Thanks for pointing this out.

I think this issue is less severe from this library point of view. The reasons are:

1. The "azure-storage" gem uses the default settings of nokogiri which is secure against this flavor of XXE.
2. The usage of nokogiri is limited to parse the response body from the Azure Storage service. I am pretty sure that the service will never return any XML element that requires an external entity. (I highly suggest to use https to perform the request to protect the cliet from tampering or spoofing).

Considering the risks of using other libraries, I'd prefer to wait for the fix in upstreams.

**Comment by habibbhutto** [comment]
Hi @yaxia,

Thanks for the reply. I agree with you it is less severe if used with default values. Thanks for confirming that "azure-storage" is using it with default values and highlighting its limited role in "azure-storage". That is helpful.

yep, I understand. I would keep an eye on upstream as well.
