### ISSUE TITLE
Missing License information

### ISSUE THREAD

**Issue by avronr** [Azure/azure-storage-ruby#176]
The repo is missing license information. Is this software even open-source? Please add a dedicated LICENSE file.

**Comment by yaxia** [comment]
The license declaration is in the folder of each service, since they are release separately.

https://github.com/Azure/azure-storage-ruby/blob/master/common/LICENSE.txt
https://github.com/Azure/azure-storage-ruby/blob/master/blob/LICENSE.txt
https://github.com/Azure/azure-storage-ruby/blob/master/file/LICENSE.txt
https://github.com/Azure/azure-storage-ruby/blob/master/queue/LICENSE.txt
https://github.com/Azure/azure-storage-ruby/blob/master/table/LICENSE.txt

**Comment by avronr** [comment]
Thanks for replying. :D
