### ISSUE TITLE
Dependency problem with faraday-middleware 1.1.0

### ISSUE THREAD

**Issue by jlavanchy** [Azure/azure-storage-ruby#196]
Hello, 

I have a dependency problem with the gem azure-storage-common. This gem is using faraday-middleware version 1.0.0.rc1. 

We are using azure-storage-blob with Chef in order to download resources from Azure. The last version of Chef (17.4) ship with the last version of Faraday-middleware (1.1.0) released on July 31, 2021. Which leads to Chef crashing in our tests and production servers running the last version. 

For the time being, we rollbacked to the previous minor version of Chef on our end which is using faraday-middleware version 1.0.0. 

Could you please review and try to fix this issue? Thanks in advance!

Julien.

**Comment by jlavanchy** [comment]
Any news on this?

**Comment by nertzy** [comment]
In the future, it would be better if dependencies were not so specific.

Instead of
```ruby
"~> 1.0.0.rc1"
```

It could have been
```ruby
"~> 1.0", ">= 1.0.0.rc1"
```

or something similar. That would allow versions 1.1, 1.2, etc. I believe this was the original intent since there is also a dependency on `faraday ~> 1.0` 

The fact that using an `rc1` version is allowed should not also make the version restriction more strict, in my opinion.

**Comment by jlavanchy** [comment]
#206

**Comment by jlavanchy** [comment]
#206

**Comment by nertzy** [comment]
Solved for me in the gems released yesterday.

**Comment by jlavanchy** [comment]
yes for me too thanks everyone! I will close this issue.
