### ISSUE TITLE
Unable to get full list Blobs in a container

### ISSUE THREAD

**Issue by ronmkr** [Azure/azure-storage-ruby#65]
I  am trying to list all blobs in a storage account
But I am just getting few out of hundreds using   `list_blob`

blobs = blob_service.list_blobs(container_name)

```
def blockblob_operations(blob_service)
   containers = blob_service.list_containers()
   containers.each do |container|
   puts "Container Name: #{container.name}"
   end
   # List all the blobs in the container
   puts 'List Blobs in Container'
   container_name = 'name'
   blobs = blob_service.list_blobs(container_name)
   blobs.each do |blob|
puts "#{blob.name} "
end
```

This only shows 6 blobs in the container but there are more than that
I tried using other options too 
But got the same output

**Comment by yaxia** [comment]
It could be caused by the uncompleted list operation at the server side. In this case, the client need to perform another list operation. You might want to add a debug filter to check whether the server returns a `NextMarker` in the response of the list operation.
``` ruby
def blockblob_operations(blob_service)
  containers = blob_service.list_containers()
  containers.each do |container|
    puts "Container Name: #{container.name}"
  end
  
  # List all the blobs in the container
  puts 'List Blobs in Container'
  container_name = 'name'
   
  # Add the debugger filter for inspect the list_blobs response
  blob_service.with_filter Azure::Core::Http::DebugFilter.new
  blobs = blob_service.list_blobs(container_name)
  blobs.each do |blob|
    puts "#{blob.name}"
  end
end
```
If you see something like `<NextMarker>2!68!MDAwMDA1ITEudHh0IT--</NextMarker>` in the response, then we can confirm the issue. 

The list API has supported passing `marker` as an option. You may change the code of listing blobs like:
```ruby
  blobs = blob_service.list_blobs(container_name)
  blobs.each do |blob|
    puts "#{blob.name} "
  end

  while blobs.continuation_token && blobs.continuation_token.length > 0 do
    blobs = blob_service.list_blobs(container_name, marker: blobs.continuation_token)
    blobs.each do |blob|
      puts "#{blob.name} "
    end
  end
```

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
