### ISSUE TITLE
azure-storage-ruby gem should support using nokogiri >= 1.7.1

### ISSUE THREAD

**Issue by thausler786** [Azure/azure-storage-ruby#82]
`nokogiri` has recently been updated to address several CVEs in the `libxml2` library: [link](https://github.com/sparklemotion/nokogiri/issues/1615).

`azure-storage` is locked to versions of `nokogiri` that conform to ~> 1.6.0, which prevents us from updating our `nokogiri` to the patched version.

Is there anything preventing `azure-storage` from using newer versions of `nokogiri`? We would like to update our `azure-storage` to a version that supports `nokogiri` 1.7.1.

**Comment by yaxia** [comment]
@thausler786 Thanks for your suggestion. The reason we stick on `nokogiri 1.6` is for the old version compatibility:
1. `nokogiri 1.7` requires Ruby 2.1 at least which doesn't match with the support matrix of `azure-storage`.
2. As a part of Azure services, we need align with the version requirement of the [Azure](https://rubygems.org/gems/azure) gem.

Since the CVEs are important to us, we will figure out a solution, please stay tuned. Thanks.

BTW, which version of Ruby are you using?

**Comment by thausler786** [comment]
@yaxia , we are using 2.3.3.  Thanks!

**Comment by flavorjones** [comment]
@yaxia Rubygems is smart enough to install the right version of a gem for the ruby that's being used.

Example:

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle install
...
Installing nokogiri 1.6.8.1 with native extensions
...
```

if I change the gemspec to 

```
  s.add_runtime_dependency('nokogiri',                '~> 1.6', '< 1.8')
```

then with ruby 2.4.0 I'll get the most recent Nokogiri with patches

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle update nokogiri
...
Using nokogiri 1.7.1 (was 1.6.8.1)
...
```

but with ruby 1.9 I'll still get the 1.6.8.1 version because Rubygems is smart enough

```
$ ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ bundle update nokogiri
...
Using nokogiri 1.6.8.1
...
```

at least for recent versions of bundler (I tested above with bundler 1.14.6). It looks like older versions of bundler aren't smart enough to use the `s.required_ruby_version` gemspec constraint.

I'd like to submit a PR for this.

**Comment by flavorjones** [comment]
I've submitted PR #83 to help users of later rubies use later versions of nokogiri.

**Comment by Gerg** [comment]
Hello, has there been any progress on this? This is blocking us from upgrading to a secure version of nokogiri. Thanks!

**Comment by yaxia** [comment]
The PR #83 has been merged. Once we have the tests done, we will release a new version. Thanks for your patience.

**Comment by yaxia** [comment]
Please try the [0.12.1-preview](https://rubygems.org/gems/azure-storage/versions/0.12.1.preview) release. Thanks.
