### ISSUE TITLE
azure-storage can't work with rspec 3.2.0+

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-storage-ruby#87]
https://github.com/rspec/rspec-mocks/issues/1161

Could you please confirm the bug in `azure-storage` which is described in the above issue?

**Comment by yaxia** [comment]
@bingosummer The error message you saw was caused by missing parameter in initializing the `Azure::Storage::Client` class, which requires storage account access information be set either in the environment or in the `options` argument.

I don't know how exactly `allow(client).to receive(:storage_table_host=)` work in rspec. Could you please share more on how are those storage account information set in your project? Why the [commit](https://github.com/rspec/rspec-support/issues/317) worked around the issue?

**Comment by yaxia** [comment]
This issue is caused by the Azure::Storage::client is used in `method_missing`. I will fix it in next release, please stay tuned. Thanks.

**Comment by bingosummer** [comment]
Hi @yaxia, how is this issue going?

**Comment by yaxia** [comment]
@katmsft is working on it and will have the fix in the upcoming release. Thanks.

**Comment by katmsft** [comment]
Fixed in 0.14.0. @bingosummer check it out!
